version: '3.7'

services:
    client:
          container_name: frontend
          image: client:latest 
          build: 
            context: ./client
            dockerfile: Dockerfile 
          Volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
          ports: 
            - "8080:80"
          restart: always
    flask-server:
          container_name: backend
          image: flask-server:latest
          build: 
            context: ./flash-server
            dockerfile: Dockerfile
          ports:
            - "8000:8000"
          restart: always